Add getCanvasContainer to types
visgl/react-map-gl pull request #2356
Opened 2024-02-15 10:23 UTC by georgemoon

Both MapLibre GL and Mapbox GL have a function 'getCanvasContainer':

- https://github.com/mapbox/mapbox-gl-js/blob/bb51e3ba7cceef993628f6c85eef69435d902e4c/src/ui/map.js#L788
- https://github.com/maplibre/maplibre-gl-js/blob/3bea9a10acf741caf0913eb3792ef0a268f6fbe3/src/ui/map.ts#L2837

I would like to suggest that it be added to the types if possible. The attached is a simple pull request adding this type.

Thanks!

2024-02-15 17:40 UTC, Pessimistress requested changes
This type is only used for internal type check. Map methods that are exposed to the user come from `@types/mapbox-gl` or `maplibre-gl`.

2024-02-16 11:08 UTC, georgemoon commented
The type was being exposed in the context of using "useControl" from "react-map-gl/maplibre".
I can see if I can do a minimal replication of the bug if that would be useful?

2024-02-18 00:02 UTC, Pessimistress commented
I see. Yes, that would be a bug.

2024-12-19 07:32 UTC, Pessimistress approved these changes

2024-12-19 07:38 UTC, merged